import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, ProviderIdentity, type LegalSection } from "@/components/legal-page";

export const metadata: Metadata = { title:"Términos y condiciones | Papeleta", description:"Condiciones de contratación y uso de Papeleta en Argentina.", alternates:{canonical:"/terminos"} };
const sections: LegalSection[] = [
 {id:"proveedor",title:"1. Quién presta el servicio",content:<><p>Papeleta es una plataforma argentina para crear, contratar, publicar y compartir invitaciones digitales. Los datos del proveedor y su canal de atención son:</p><ProviderIdentity/><p>Los datos registrales aplicables también se mostrarán durante la contratación y en el comprobante.</p></>},
 {id:"alcance",title:"2. Alcance y prioridad de la ley",content:<><p>Estos términos rigen para visitantes, titulares de cuenta, organizadores y personas que contratan. Si contratás como destinatario final, se aplican la Ley 24.240, el Código Civil y Comercial y las demás normas argentinas de consumo.</p><p>Ninguna cláusula limita derechos irrenunciables. Ante duda se utilizará la interpretación más favorable al consumidor. La <Link href="/privacidad">Política de privacidad</Link>, la <Link href="/politica-de-uso">Política de uso</Link> y la <Link href="/reembolsos">Política de cancelación y reembolsos</Link> integran estas condiciones.</p></>},
 {id:"servicio",title:"3. Servicio, planes y contratación",content:<><p>El servicio permite seleccionar una plantilla, cargar contenido, guardar un borrador, contratar un plan y publicar una URL. Las prestaciones, límites, vigencia y precio total aplicables son los informados antes de confirmar la compra. Invitación incluye la comunicación completa del evento; Invitación + Invitados suma confirmaciones y herramientas de organización.</p><p>La contratación se confirma cuando Papeleta valida el pago y la orden. Antes de pagar podrás revisar y corregir los datos. Conservaremos constancia electrónica de la operación.</p></>},
 {id:"cuenta",title:"4. Cuenta y seguridad",content:<><p>Debés proporcionar datos verdaderos, proteger tus credenciales y avisar ante accesos no autorizados. La cuenta es personal. Podemos realizar verificaciones razonables de identidad y seguridad sin convertirlas en obstáculos para ejercer derechos.</p><p>Quien actúa por otra persona o entidad declara tener autorización suficiente.</p></>},
 {id:"contenido",title:"5. Contenido y datos de invitados",content:<><p>Conservás tus derechos sobre textos, imágenes, música y archivos. Nos otorgás una licencia limitada y no exclusiva únicamente para alojar, adaptar técnicamente y mostrar ese material en la invitación mientras resulte necesario.</p><p>Sos responsable de contar con permisos y bases legales para usar contenido y datos de invitados. No publiques datos bancarios sensibles, documentos, información médica ni datos de menores que no sean necesarios.</p></>},
 {id:"pago",title:"6. Precio, pago y publicación",content:<><p>El precio total en pesos argentinos, impuestos, promociones y financiación se informan antes del checkout. El pago autoservicio se procesa mediante Mercado Pago. Papeleta no cambia el plan efectivo ni publica el evento hasta recibir confirmación válida.</p><p>Un pago pendiente no equivale a aprobación. Los cobros duplicados, importes incorrectos o errores del procesador se revisarán y resolverán conforme a la ley.</p></>},
 {id:"vigencia",title:"7. Vigencia y disponibilidad",content:<><p>La duración y límites son los informados al contratar. Podés editar dentro de las funciones del plan. Podemos realizar mantenimiento y actualizaciones procurando minimizar interrupciones.</p><p>Mercado Pago, Google Maps y las redes de telecomunicaciones son servicios externos. No controlamos su disponibilidad, pero gestionaremos nuestras integraciones con diligencia.</p></>},
 {id:"baja",title:"8. Baja, suspensión y eliminación",content:<><p>Podés solicitar la <Link href="/baja">baja del servicio</Link> sin iniciar sesión. Dentro de 24 horas informaremos un código de identificación y las medidas adoptadas. La baja no elimina derechos de arrepentimiento, garantía o reclamo.</p><p>Podemos limitar una cuenta por seguridad, fraude, orden legal o infracción grave. Salvo urgencia, comunicaremos el motivo y permitiremos corregir o apelar.</p></>},
 {id:"arrepentimiento",title:"9. Arrepentimiento e incumplimiento",content:<><p>En contrataciones a distancia existe el derecho de revocación previsto por la normativa, sujeto a excepciones legales. Se ejerce desde el <Link href="/arrepentimiento">BOTÓN DE ARREPENTIMIENTO</Link>, visible y sin login.</p><p>Ante incumplimiento conservás las opciones del artículo 10 bis de la Ley 24.240, incluida la rescisión con restitución cuando corresponda, sin perjuicio de daños.</p></>},
 {id:"responsabilidad",title:"10. Responsabilidad",content:<p>Papeleta responde según la legislación aplicable. No controla la veracidad del contenido del organizador ni los actos de invitados. Toda limitación rige sólo en la medida legal y nunca excluye dolo, culpa grave, seguridad, incumplimiento legal ni derechos del consumidor.</p>},
 {id:"cambios",title:"11. Cambios y comunicaciones",content:<p>Podemos actualizar estas condiciones por cambios legales, técnicos o del servicio. Los cambios materiales se comunicarán con antelación razonable y regirán hacia el futuro; no reducirán derechos adquiridos.</p>},
 {id:"ley",title:"12. Ley, reclamos y jurisdicción",content:<><p>Rige la ley argentina. Si sos consumidor, el conflicto se tramitará ante la autoridad o tribunales competentes conforme a tu domicilio y las reglas imperativas; no imponemos prórrogas inválidas.</p><p>También podés acudir a la <a href="https://www.argentina.gob.ar/produccion/consumidor" target="_blank" rel="noreferrer">Ventanilla Única Federal de Defensa del Consumidor</a>.</p></>},
];
export default function TermsPage(){return <LegalPage eyebrow="BASES Y CONDICIONES" title="Términos y condiciones" lead="Reglas claras para crear, contratar y compartir una invitación en Papeleta." notice={<><strong>Lo esencial</strong>Antes de pagar verás el precio total y las funciones. Tus derechos legales de arrepentimiento, garantía y reclamo no pueden ser renunciados.</>} sections={sections}/>}
