import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/legal-page";
export const metadata:Metadata={title:"Política de uso | Papeleta",description:"Reglas de uso aceptable y contenido permitido en Papeleta.",alternates:{canonical:"/politica-de-uso"}};
const sections:LegalSection[]=[
 {id:"objetivo",title:"1. Objetivo y alcance",content:<p>Esta política protege a organizadores, invitados, terceros y a la plataforma. Se aplica a cuentas, invitaciones, RSVP, álbumes, trivia, archivos e integraciones.</p>},
 {id:"permitido",title:"2. Uso permitido",content:<p>Podés organizar eventos lícitos, crear invitaciones propias o autorizadas, administrar respuestas y compartir contenido respecto del cual tengas derechos y consentimiento suficiente.</p>},
 {id:"contenido",title:"3. Contenido prohibido",content:<><p>No está permitido contenido que:</p><ul><li>sea ilegal, fraudulento, engañoso o suplante identidades;</li><li>vulnere propiedad intelectual, imagen, honor, privacidad o datos personales;</li><li>promueva odio, discriminación, acoso, amenazas, violencia o explotación sexual;</li><li>exponga indebidamente a menores o información sensible;</li><li>incluya malware, phishing, spam o enlaces para robar credenciales;</li><li>publique datos bancarios, contraseñas o documentos sin necesidad y autorización.</li></ul></>},
 {id:"tecnico",title:"4. Conductas técnicas prohibidas",content:<ul><li>eludir autenticación, controles, cuotas o límites del plan;</li><li>probar vulnerabilidades sin autorización escrita;</li><li>extraer datos automáticamente, saturar o interferir el servicio;</li><li>revender accesos, compartir credenciales o manipular pagos;</li><li>usar datos de invitados para publicidad no consentida.</li></ul>},
 {id:"organizador",title:"5. Deberes del organizador",content:<p>El organizador debe informar a sus invitados, recolectar sólo datos necesarios, mantener información correcta, atender solicitudes vinculadas con el evento y eliminar contenido que ya no corresponda conservar.</p>},
 {id:"moderacion",title:"6. Reportes y moderación",content:<p>Reportá contenido a <a href="mailto:hola@papeleta.com.ar?subject=Reporte%20de%20contenido">hola@papeleta.com.ar</a> con URL y motivo. Evaluaremos gravedad, contexto, reincidencia y riesgo. Podemos retirar contenido, limitar funciones, preservar evidencia mínima o bloquear cuando sea proporcional o exigido por ley.</p>},
 {id:"medidas",title:"7. Medidas y revisión",content:<p>Salvo fraude, riesgo urgente u orden de autoridad, procuraremos avisar y permitir corrección. Podés pedir revisión. Una suspensión no elimina derechos de consumo ni impide solicitar exportación o eliminación cuando corresponda.</p>},
 {id:"prioridad",title:"8. Prioridad de la ley",content:<p>Esta política no autoriza decisiones discriminatorias o arbitrarias. Si una regla entra en conflicto con la legislación argentina, prevalece la ley.</p>},
];
export default function UsagePolicy(){return <LegalPage eyebrow="CONVIVENCIA Y SEGURIDAD" title="Política de uso" lead="Qué podés hacer, qué conductas no están permitidas y cómo actuamos ante un reporte." notice={<><strong>Regla central</strong>Usá únicamente contenido y datos que tengas derecho a utilizar, y recolectá de tus invitados sólo lo necesario.</>} sections={sections}/>}
