"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import "./panels.css";
import { RoleBadge, useAccountRole } from "@/components/account-role";
import { getBrowserSupabase } from "@/lib/supabase-browser";

type Payment = { id: string; plan: string; amount: number; status: string; provider?: string; receipt_url?: string; events?: { title: string; slug: string } };
type Upgrade = { id: string; source_plan: string; target_plan: string; amount: number; status: string; events?: { title: string; slug: string } };
type AdminEvent = { id: string; title: string; slug: string; starts_at: string | null; status: string; plan: string; payment_status: string; profiles?: { full_name: string } | null };
type User = { id: string; fullName: string; email: string; role: "admin" | "organizer"; eventCount: number; lastActivity: string | null };
type ConfirmAction = { title: string; description: string; confirmLabel: string; tone?: "danger"; run: () => Promise<void> };

const money = (value: number) => value.toLocaleString("es-AR", { style: "currency", currency: "ARS", maximumFractionDigits: 0 });
const labels: Record<string, string> = { approved: "Aprobado", pending: "Pendiente", rejected: "Rechazado", draft: "Borrador", published: "Publicado", finished: "Finalizado", unpaid: "Sin pagar" };
async function api(path: string, init?: RequestInit) { const token = (await getBrowserSupabase()?.auth.getSession())?.data.session?.access_token; return fetch(path, { ...init, headers: { authorization: `Bearer ${token ?? ""}`, "content-type": "application/json", ...(init?.headers ?? {}) } }); }

export function AdminPayments() {
  const { account, error, loading } = useAccountRole();
  const [tab, setTab] = useState<"overview" | "operations" | "events" | "users">("overview");
  const [days, setDays] = useState(30); const [notice, setNotice] = useState(""); const [summary, setSummary] = useState<any>();
  const [payments, setPayments] = useState<Payment[]>([]); const [upgrades, setUpgrades] = useState<Upgrade[]>([]); const [events, setEvents] = useState<AdminEvent[]>([]); const [users, setUsers] = useState<User[]>([]);
  const [eventQuery, setEventQuery] = useState(""); const [eventStatus, setEventStatus] = useState("all"); const [userQuery, setUserQuery] = useState(""); const [confirmAction, setConfirmAction] = useState<ConfirmAction>(); const [running, setRunning] = useState(false);
  const load = async () => { if (account?.role !== "admin") return; setNotice("Cargando panel…"); try { const responses = await Promise.all([api(`/api/admin/overview?days=${days}`), api("/api/admin/payments"), api("/api/admin/upgrades"), api("/api/admin/events"), api(`/api/admin/users?q=${encodeURIComponent(userQuery)}`)]); const bodies = await Promise.all(responses.map((response) => response.json())); const failed = responses.findIndex((response) => !response.ok); if (failed >= 0) throw new Error(bodies[failed].error); setSummary(bodies[0]); setPayments(bodies[1].payments); setUpgrades(bodies[2].upgrades); setEvents(bodies[3].events); setUsers(bodies[4].users); setNotice(""); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "No pudimos cargar el panel."); } };
  useEffect(() => { void load(); }, [account?.role, days, userQuery]);
  const run = async () => { if (!confirmAction) return; setRunning(true); try { await confirmAction.run(); setConfirmAction(undefined); } finally { setRunning(false); } };
  const review = (kind: "payments" | "upgrades", id: string, decision: "approved" | "rejected") => setConfirmAction({ title: decision === "approved" ? "Confirmar aprobación" : "Confirmar rechazo", description: `Esta acción actualizará el estado de la solicitud.`, confirmLabel: decision === "approved" ? "Aprobar" : "Rechazar", tone: decision === "rejected" ? "danger" : undefined, run: async () => { const response = await api(`/api/admin/${kind}`, { method: "PATCH", body: JSON.stringify(kind === "payments" ? { paymentId: id, decision } : { upgradeId: id, decision }) }); const body = await response.json(); setNotice(response.ok ? "Operación actualizada." : body.error); if (response.ok) await load(); } });
  const publish = (event: AdminEvent) => setConfirmAction({ title: "Publicar por transferencia", description: `Publicarás “${event.title}” y se registrará un pago por transferencia aprobado. Esta acción habilita su invitación pública.`, confirmLabel: "Publicar evento", run: async () => { const response = await api("/api/admin/events", { method: "PATCH", body: JSON.stringify({ eventId: event.id, action: "publish" }) }); const body = await response.json(); setNotice(response.ok ? "Evento publicado por transferencia." : body.error); if (response.ok) await load(); } });
  const changeRole = (user: User) => { const role = user.role === "admin" ? "organizer" : "admin"; setConfirmAction({ title: "Cambiar rol", description: `${user.fullName} pasará a ser ${role === "admin" ? "Administrador" : "Organizador"}.`, confirmLabel: "Confirmar cambio", run: async () => { const response = await api("/api/admin/users", { method: "PATCH", body: JSON.stringify({ userId: user.id, role }) }); const body = await response.json(); setNotice(response.ok ? "Rol actualizado y auditado." : body.error); if (response.ok) await load(); } }); };
  const deleteUser = (user: User) => setConfirmAction({ title: "Eliminar cuenta y eventos", description: `Eliminarás permanentemente a ${user.email}, incluidos sus ${user.eventCount} eventos, invitaciones, invitados y respuestas. Esta acción no se puede deshacer.`, confirmLabel: "Eliminar definitivamente", tone: "danger", run: async () => { const response = await api(`/api/admin/users?userId=${encodeURIComponent(user.id)}`, { method: "DELETE" }); const body = await response.json(); setNotice(response.ok ? "Cuenta eliminada." : body.error); if (response.ok) await load(); } });
  const filteredEvents = useMemo(() => events.filter((event) => (eventStatus === "all" || event.status === eventStatus) && `${event.title} ${event.slug} ${event.profiles?.full_name ?? ""}`.toLowerCase().includes(eventQuery.toLowerCase())), [events, eventQuery, eventStatus]);
  if (loading) return <main className="panelShell"><Loading label="Comprobando permisos…" /></main>;
  if (error || account?.role !== "admin") return <main className="panelShell"><AccessDenied message={error} /></main>;
  const paymentMetrics = summary?.metrics.payments ?? {};
  return <main className="panelShell adminShell"><header className="panelTop"><div><p className="eyebrow">PANEL DE ADMINISTRADOR</p><h1>Administración</h1><p>Gestioná operaciones, eventos y cuentas desde un solo lugar.</p></div><RoleBadge role={account.role} /></header><nav className="adminTabs" aria-label="Secciones de administración">{(["overview", "operations", "events", "users"] as const).map((item) => <button className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item}>{({ overview: "Resumen", operations: "Operaciones", events: "Eventos", users: "Usuarios" })[item]}</button>)}</nav>{notice && <p className="notice" role="status">{notice}</p>}
    {tab === "overview" && <Overview days={days} setDays={setDays} summary={summary} paymentMetrics={paymentMetrics} goTo={setTab} />}
    {tab === "operations" && <Operations payments={payments} upgrades={upgrades} review={review} />}
    {tab === "events" && <Events events={filteredEvents} query={eventQuery} setQuery={setEventQuery} status={eventStatus} setStatus={setEventStatus} publish={publish} />}
    {tab === "users" && <Users users={users} userQuery={userQuery} setUserQuery={setUserQuery} currentUserId={account.userId} changeRole={changeRole} deleteUser={deleteUser} />}
    {confirmAction && <ConfirmDialog action={confirmAction} running={running} onCancel={() => setConfirmAction(undefined)} onConfirm={() => void run()} />}
  </main>;
}
function Overview({ days, setDays, summary, paymentMetrics, goTo }: any) { return <><div className="panelToolbar"><label>Período <select value={days} onChange={(event) => setDays(Number(event.target.value))}><option value={7}>Últimos 7 días</option><option value={30}>Últimos 30 días</option><option value={90}>Últimos 90 días</option><option value={0}>Histórico</option></select></label></div><section className="metricsGrid"><Metric value={summary?.metrics.events.total ?? 0} label="Eventos creados" /><Metric value={summary?.metrics.events.published ?? 0} label="Invitaciones publicadas" /><Metric value={money(paymentMetrics.approved?.amount ?? 0)} label="Cobrado" /><Metric value={summary?.metrics.activeOrganizers ?? 0} label="Organizadores activos" /></section><section className="panelGrid"><article className="panelCard"><p className="eyebrow">PARA REVISAR</p><h2>Acciones pendientes</h2><div className="actionList"><button onClick={() => goTo("operations")}>{paymentMetrics.pending?.count ?? 0} pagos pendientes <span>→</span></button><button onClick={() => goTo("operations")}>{summary?.metrics.upgrades.pending ?? 0} mejoras por revisar <span>→</span></button><button onClick={() => goTo("events")}>{summary?.metrics.events.pending ?? 0} borradores por publicar <span>→</span></button></div></article><article className="panelCard subduedCard"><p className="eyebrow">ESTADO DEL PERÍODO</p><h2>Visión rápida</h2><dl><div><dt>Pagos rechazados</dt><dd>{paymentMetrics.rejected?.count ?? 0}</dd></div><div><dt>Eventos en borrador</dt><dd>{summary?.metrics.events.pending ?? 0}</dd></div></dl></article></section></> }
function Operations({ payments, upgrades, review }: { payments: Payment[]; upgrades: Upgrade[]; review: (kind: "payments" | "upgrades", id: string, decision: "approved" | "rejected") => void }) { const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [plan, setPlan] = useState("all"); const match = (item: { status: string; plan: string; events?: { title: string; slug: string } }) => (status === "all" || item.status === status) && (plan === "all" || item.plan === plan) && `${item.events?.title ?? ""} ${item.events?.slug ?? ""}`.toLowerCase().includes(query.toLowerCase()); const visiblePayments = payments.filter(match); const visibleUpgrades = upgrades.filter((upgrade) => match({ ...upgrade, plan: upgrade.target_plan })); return <><FilterBar query={query} setQuery={setQuery} status={status} setStatus={setStatus} plan={plan} setPlan={setPlan} placeholder="Buscar por evento o URL" /><DataTable headings={["Evento", "Plan", "Importe", "Estado", "Acciones"]} empty="No hay pagos con estos filtros.">{visiblePayments.map((payment) => <tr key={payment.id}><td><strong>{payment.events?.title ?? "Evento eliminado"}</strong><small>/{payment.events?.slug}</small></td><td>{payment.plan}</td><td>{money(payment.amount)}</td><td><Badge status={payment.status} /></td><td><div className="panelActions">{payment.receipt_url && <a href={payment.receipt_url} target="_blank" rel="noreferrer">Comprobante</a>}{payment.status === "pending" && payment.provider !== "mercadopago" && <><button onClick={() => review("payments", payment.id, "approved")}>Aprobar</button><button className="dangerAction" onClick={() => review("payments", payment.id, "rejected")}>Rechazar</button></>}{payment.status === "pending" && payment.provider === "mercadopago" && <span className="lockedAction">Mercado Pago</span>}</div></td></tr>)}</DataTable><section className="adminSection"><div className="sectionHeading"><div><p className="eyebrow">CAMBIOS DE PLAN</p><h2>Solicitudes de mejora</h2></div></div><DataTable headings={["Evento", "Cambio", "Saldo", "Estado", "Acciones"]} empty="No hay mejoras con estos filtros.">{visibleUpgrades.map((upgrade) => <tr key={upgrade.id}><td><strong>{upgrade.events?.title ?? "Evento eliminado"}</strong><small>/{upgrade.events?.slug}</small></td><td>{upgrade.source_plan} → {upgrade.target_plan}</td><td>{money(upgrade.amount)}</td><td><Badge status={upgrade.status} /></td><td><div className="panelActions">{upgrade.status === "pending" && <><button onClick={() => review("upgrades", upgrade.id, "approved")}>Aprobar</button><button className="dangerAction" onClick={() => review("upgrades", upgrade.id, "rejected")}>Rechazar</button></>}</div></td></tr>)}</DataTable></section></> }
function Events({ events, query, setQuery, status, setStatus, publish }: { events: AdminEvent[]; query: string; setQuery: (value: string) => void; status: string; setStatus: (value: string) => void; publish: (event: AdminEvent) => void }) { return <><FilterBar query={query} setQuery={setQuery} status={status} setStatus={setStatus} placeholder="Buscar por evento, URL u organizador" /><DataTable headings={["Evento", "Organizador", "Plan", "Estado", "Acciones"]} empty="No encontramos eventos con estos filtros.">{events.map((event) => <tr key={event.id}><td><strong>{event.title}</strong><small>/{event.slug}</small></td><td>{event.profiles?.full_name ?? "Sin nombre"}</td><td>{event.plan}</td><td><Badge status={event.status} /></td><td><div className="panelActions">{event.status === "published" ? <Link href={`/e/${event.slug}`} target="_blank">Ver invitación ↗</Link> : <button className="primaryAction" onClick={() => publish(event)}>Publicar por transferencia</button>}</div></td></tr>)}</DataTable></> }
function Users({ users, userQuery, setUserQuery, currentUserId, changeRole, deleteUser }: { users: User[]; userQuery: string; setUserQuery: (value: string) => void; currentUserId: string; changeRole: (user: User) => void; deleteUser: (user: User) => void }) { const copyEmail=async(email:string)=>{try{await navigator.clipboard.writeText(email)}catch{/* Clipboard access is optional. */}};return <><div className="panelToolbar"><label className="searchField"><span>Buscar cuenta</span><input placeholder="Nombre o email" value={userQuery} onChange={(event) => setUserQuery(event.target.value)} /></label></div><DataTable headings={["Cuenta", "Rol", "Eventos", "Actividad", "Acciones"]} empty="No hay usuarios que coincidan.">{users.map((user) => <tr key={user.id}><td><strong>{user.fullName}</strong><span className="emailValue" title={user.email}>{user.email}</span><button className="copyEmail" onClick={() => void copyEmail(user.email)}>Copiar email</button></td><td><RoleBadge role={user.role} /></td><td>{user.eventCount}</td><td>{user.lastActivity ? new Intl.DateTimeFormat("es-AR", { dateStyle: "short" }).format(new Date(user.lastActivity)) : "Sin eventos"}</td><td><div className="panelActions">{user.id !== currentUserId && <><button onClick={() => changeRole(user)}>Hacer {user.role === "admin" ? "organizador" : "administrador"}</button><button className="dangerAction" onClick={() => deleteUser(user)}>Eliminar</button></>}</div></td></tr>)}</DataTable></> }
function FilterBar({ query, setQuery, status, setStatus, plan, setPlan, placeholder }: { query: string; setQuery: (value: string) => void; status: string; setStatus: (value: string) => void; plan?: string; setPlan?: (value: string) => void; placeholder: string }) { return <div className="panelToolbar"><input placeholder={placeholder} value={query} onChange={(event) => setQuery(event.target.value)} /><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">Todos los estados</option><option value="pending">Pendientes</option><option value="approved">Aprobados</option><option value="rejected">Rechazados</option><option value="draft">Borradores</option><option value="published">Publicados</option><option value="finished">Finalizados</option></select>{setPlan && <select value={plan} onChange={(event) => setPlan(event.target.value)}><option value="all">Todos los planes</option><option value="standard">Estándar</option><option value="premium">Premium</option><option value="premium_plus">Premium Plus+</option></select>}</div> }
function DataTable({ headings, children, empty }: { headings: string[]; children: React.ReactNode; empty: string }) { const hasRows = Array.isArray(children) ? children.length > 0 : Boolean(children); return <div className="tableCard"><div className="tableWrap"><table className="panelTable"><thead><tr>{headings.map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{children}</tbody></table></div>{!hasRows && <Empty title={empty} />}</div> }
function Metric({ value, label }: { value: string | number; label: string }) { return <article className="metricCard"><b>{value}</b><span>{label}</span></article> }
function Badge({ status }: { status: string }) { return <span className={`paymentBadge ${status}`}>{labels[status] ?? status}</span> }
function Empty({ title }: { title: string }) { return <div className="emptyState"><b>{title}</b><span>Probá ajustar los filtros o volvé más tarde.</span></div> }
function Loading({ label }: { label: string }) { return <div className="emptyState"><b>{label}</b></div> }
function AccessDenied({ message }: { message?: string }) { return <><p className="eyebrow">ACCESO RESTRINGIDO</p><h1>Este panel es solo para administradores.</h1><p>{message ?? "Tu cuenta no tiene permisos administrativos."}</p><Link className="button dark" href="/mis-eventos">Ir a mis eventos</Link></> }
function ConfirmDialog({ action, running, onCancel, onConfirm }: { action: ConfirmAction; running: boolean; onCancel: () => void; onConfirm: () => void }) { return <div className="dialogBackdrop" role="presentation"><section className="actionDialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><p className="eyebrow">CONFIRMACIÓN</p><h2 id="dialog-title">{action.title}</h2><p>{action.description}</p><div><button className="button outline" disabled={running} onClick={onCancel}>Cancelar</button><button className={`button ${action.tone === "danger" ? "dangerButton" : "dark"}`} disabled={running} onClick={onConfirm}>{running ? "Procesando…" : action.confirmLabel}</button></div></section></div> }
