"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import "./panels.css";
import { RoleBadge, useAccountRole } from "@/components/account-role";
import { getBrowserSupabase } from "@/lib/supabase-browser";

type Payment={id:string;plan:string;amount:number;status:string;provider?:string;organizer_note?:string;admin_note?:string;receipt_url?:string;created_at:string;events?:{title:string;slug:string}};
type Upgrade={id:string;source_plan:string;target_plan:string;amount:number;status:string;admin_note?:string;created_at:string;events?:{title:string;slug:string}};
type AdminEvent={id:string;title:string;slug:string;starts_at:string|null;status:string;plan:string;payment_status:string;profiles?:{full_name:string}|null};
type User={id:string;fullName:string;email:string;role:"admin"|"organizer";eventCount:number;lastActivity:string|null};
const money=(value:number)=>`$${value.toLocaleString("es-AR")}`;
const label=(status:string)=>({approved:"Aprobado",pending:"Pendiente",rejected:"Rechazado",draft:"Borrador",published:"Publicado",finished:"Finalizado"}[status]??status);

async function request(path:string, init?:RequestInit){const token=(await getBrowserSupabase()?.auth.getSession())?.data.session?.access_token;return fetch(path,{...init,headers:{authorization:`Bearer ${token??""}`,"content-type":"application/json",...(init?.headers??{})}})}

export function AdminPayments(){
  const {account,error,loading}=useAccountRole(); const[tab,setTab]=useState<"overview"|"operations"|"events"|"users">("overview"); const[days,setDays]=useState(30); const[notice,setNotice]=useState(""); const[summary,setSummary]=useState<any>(); const[payments,setPayments]=useState<Payment[]>([]); const[upgrades,setUpgrades]=useState<Upgrade[]>([]); const[events,setEvents]=useState<AdminEvent[]>([]); const[users,setUsers]=useState<User[]>([]); const[query,setQuery]=useState(""); const[status,setStatus]=useState("all");
  const load=async()=>{if(account?.role!=="admin")return;setNotice("Cargando panel…");try{const [summaryResponse,paymentsResponse,upgradesResponse,eventsResponse,usersResponse]=await Promise.all([request(`/api/admin/overview?days=${days}`),request("/api/admin/payments"),request("/api/admin/upgrades"),request("/api/admin/events"),request("/api/admin/users")]);const responses=[summaryResponse,paymentsResponse,upgradesResponse,eventsResponse,usersResponse];const bodies=await Promise.all(responses.map(response=>response.json()));const failed=responses.findIndex(response=>!response.ok);if(failed>=0)throw new Error(bodies[failed].error);setSummary(bodies[0]);setPayments(bodies[1].payments);setUpgrades(bodies[2].upgrades);setEvents(bodies[3].events);setUsers(bodies[4].users);setNotice("")}catch(reason){setNotice(reason instanceof Error?reason.message:"No pudimos cargar el panel.")}};
  useEffect(()=>{void load()},[account?.role,days]);
  const decide=async(kind:"payments"|"upgrades",id:string,decision:"approved"|"rejected")=>{if(!confirm(`¿${decision==="approved"?"Aprobar":"Rechazar"} esta solicitud?`))return;const response=await request(`/api/admin/${kind}`,{method:"PATCH",body:JSON.stringify(kind==="payments"?{paymentId:id,decision}:{upgradeId:id,decision})});const body=await response.json();setNotice(response.ok?"Operación actualizada.":body.error);if(response.ok)void load()};
  const changeRole=async(user:User)=>{const role=user.role==="admin"?"organizer":"admin";if(!confirm(`¿Cambiar a ${user.fullName} al rol ${role==="admin"?"Administrador":"Organizador"}?`))return;const response=await request("/api/admin/users",{method:"PATCH",body:JSON.stringify({userId:user.id,role})});const body=await response.json();setNotice(response.ok?"Rol actualizado y auditado.":body.error);if(response.ok)void load()};
  const filteredEvents=useMemo(()=>events.filter(event=>(status==="all"||event.status===status)&&(`${event.title} ${event.slug} ${event.profiles?.full_name??""}`).toLowerCase().includes(query.toLowerCase())),[events,query,status]);
  if(loading)return <main className="panelShell"><p>Comprobando permisos…</p></main>;
  if(error||account?.role!=="admin")return <main className="panelShell"><p className="eyebrow">ACCESO RESTRINGIDO</p><h1>Este panel es solo para administradores.</h1><p>{error||"Tu cuenta no tiene permisos administrativos."}</p><Link className="button dark" href="/mis-eventos">Ir a mis eventos</Link></main>;
  const paymentMetrics=summary?.metrics.payments??{};
  return <main className="panelShell"><header className="panelTop"><div><p className="eyebrow">PANEL DE ADMINISTRADOR</p><h1>Operaciones de Celebra</h1><p>Supervisá pagos, eventos, usuarios y la actividad de la plataforma.</p></div><RoleBadge role={account.role}/></header><nav className="adminTabs" aria-label="Secciones de administración">{(["overview","operations","events","users"] as const).map(item=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}>{({overview:"Resumen",operations:"Operaciones",events:"Eventos",users:"Usuarios"})[item]}</button>)}</nav>{notice&&<p className="notice" role="status">{notice}</p>}
  {tab==="overview"&&<><div className="filters"><label>Período <select value={days} onChange={event=>setDays(Number(event.target.value))}><option value={7}>Últimos 7 días</option><option value={30}>Últimos 30 días</option><option value={90}>Últimos 90 días</option><option value={0}>Histórico</option></select></label></div><section className="metricsGrid"><Metric value={summary?.metrics.events.total??0} label="Eventos creados"/><Metric value={summary?.metrics.events.published??0} label="Invitaciones publicadas"/><Metric value={money(paymentMetrics.approved?.amount??0)} label="Cobrado"/><Metric value={summary?.metrics.activeOrganizers??0} label="Organizadores activos"/></section><section className="panelGrid"><article className="panelCard"><h2>Acciones pendientes</h2><div className="actionList"><button className="button outline" onClick={()=>setTab("operations")}>{paymentMetrics.pending?.count??0} pagos pendientes</button><button className="button outline" onClick={()=>setTab("operations")}>{summary?.metrics.upgrades.pending??0} mejoras por revisar</button><button className="button outline" onClick={()=>setTab("users")}>Gestionar usuarios y roles</button></div></article><article className="panelCard"><h2>Estado del período</h2><p>{summary?.metrics.events.pending??0} eventos todavía están en borrador.</p><p>{paymentMetrics.rejected?.count??0} pagos fueron rechazados.</p></article></section></>}
  {tab==="operations"&&<Operations payments={payments} upgrades={upgrades} onDecision={decide}/>} {tab==="events"&&<><div className="filters"><input placeholder="Buscar por evento, URL u organizador" value={query} onChange={event=>setQuery(event.target.value)}/><select value={status} onChange={event=>setStatus(event.target.value)}><option value="all">Todos los estados</option><option value="draft">Borradores</option><option value="published">Publicados</option><option value="finished">Finalizados</option></select></div><EventsTable events={filteredEvents}/></>} {tab==="users"&&<UsersTable users={users} currentUserId={account.userId} onChangeRole={changeRole}/>}</main>;
}
function Metric({value,label}:{value:string|number;label:string}){return <article className="metricCard"><b>{value}</b><span>{label}</span></article>}
function Operations({payments,upgrades,onDecision}:{payments:Payment[];upgrades:Upgrade[];onDecision:(kind:"payments"|"upgrades",id:string,decision:"approved"|"rejected")=>void}){const[query,setQuery]=useState("");const[status,setStatus]=useState("all");const[plan,setPlan]=useState("all");const matches=(item:{status:string;plan?:string;events?:{title:string;slug:string}})=> (status==="all"||item.status===status)&&(plan==="all"||item.plan===plan)&&`${item.events?.title??""} ${item.events?.slug??""}`.toLowerCase().includes(query.toLowerCase());const visiblePayments=payments.filter(matches);const visibleUpgrades=upgrades.filter(item=>matches({...item,plan:item.target_plan}));return <><div className="filters"><input placeholder="Buscar por evento o URL" value={query} onChange={event=>setQuery(event.target.value)}/><select value={status} onChange={event=>setStatus(event.target.value)}><option value="all">Todos los estados</option><option value="pending">Pendientes</option><option value="approved">Aprobados</option><option value="rejected">Rechazados</option></select><select value={plan} onChange={event=>setPlan(event.target.value)}><option value="all">Todos los planes</option><option value="standard">Estándar</option><option value="premium">Premium</option><option value="premium_plus">Premium Plus+</option></select></div><OperationsList payments={visiblePayments} upgrades={visibleUpgrades} onDecision={onDecision}/></>}
function OperationsList({payments,upgrades,onDecision}:{payments:Payment[];upgrades:Upgrade[];onDecision:(kind:"payments"|"upgrades",id:string,decision:"approved"|"rejected")=>void}){return <><section className="adminSection"><h2>Pagos</h2><div className="tableWrap"><table className="panelTable"><thead><tr><th>Evento</th><th>Plan</th><th>Importe</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{payments.map(payment=><tr key={payment.id}><td><b>{payment.events?.title}</b><br/><small>/{payment.events?.slug}</small></td><td>{payment.plan}</td><td>{money(payment.amount)}</td><td><span className={`paymentBadge ${payment.status}`}>{label(payment.status)}</span></td><td><div className="panelActions">{payment.receipt_url&&<a href={payment.receipt_url} target="_blank" rel="noreferrer">Comprobante</a>}{payment.status==="pending"&&payment.provider!=="mercadopago"&&<><button onClick={()=>onDecision("payments",payment.id,"approved")}>Aprobar</button><button onClick={()=>onDecision("payments",payment.id,"rejected")}>Rechazar</button></>}{payment.status==="pending"&&payment.provider==="mercadopago"&&<span>Verificado por Mercado Pago</span>}</div></td></tr>)}</tbody></table></div>{!payments.length&&<Empty title="No hay pagos registrados."/>}</section><section className="adminSection"><h2>Solicitudes de mejora</h2><div className="tableWrap"><table className="panelTable"><thead><tr><th>Evento</th><th>Cambio</th><th>Saldo</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{upgrades.map(upgrade=><tr key={upgrade.id}><td><b>{upgrade.events?.title}</b><br/><small>/{upgrade.events?.slug}</small></td><td>{upgrade.source_plan} → {upgrade.target_plan}</td><td>{money(upgrade.amount)}</td><td><span className={`paymentBadge ${upgrade.status}`}>{label(upgrade.status)}</span></td><td><div className="panelActions">{upgrade.status==="pending"&&<><button onClick={()=>onDecision("upgrades",upgrade.id,"approved")}>Aprobar</button><button onClick={()=>onDecision("upgrades",upgrade.id,"rejected")}>Rechazar</button></>}</div></td></tr>)}</tbody></table></div>{!upgrades.length&&<Empty title="No hay mejoras pendientes."/>}</section></>}
function EventsTable({events}:{events:AdminEvent[]}){return <div className="tableWrap"><table className="panelTable"><thead><tr><th>Evento</th><th>Organizador</th><th>Plan</th><th>Estado</th><th>Invitación</th></tr></thead><tbody>{events.map(event=><tr key={event.id}><td><b>{event.title}</b><br/><small>/{event.slug}</small></td><td>{event.profiles?.full_name??"Sin nombre"}</td><td>{event.plan}</td><td><span className={`paymentBadge ${event.status}`}>{label(event.status)}</span></td><td>{event.status==="published"&&<Link href={`/e/${event.slug}`} target="_blank">Ver ↗</Link>}</td></tr>)}</tbody></table>{!events.length&&<Empty title="No encontramos eventos."/>}</div>}
function UsersTable({users,currentUserId,onChangeRole}:{users:User[];currentUserId:string;onChangeRole:(user:User)=>void}){return <div className="tableWrap"><table className="panelTable"><thead><tr><th>Cuenta</th><th>Rol</th><th>Eventos</th><th>Actividad</th><th>Acciones</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td><b>{user.fullName}</b><br/><small>{user.email}</small></td><td><RoleBadge role={user.role}/></td><td>{user.eventCount}</td><td>{user.lastActivity?new Intl.DateTimeFormat("es-AR",{dateStyle:"short"}).format(new Date(user.lastActivity)):"Sin eventos"}</td><td><div className="panelActions"><button disabled={user.id===currentUserId} onClick={()=>onChangeRole(user)}>Hacer {user.role==="admin"?"organizador":"administrador"}</button></div></td></tr>)}</tbody></table>{!users.length&&<Empty title="No hay usuarios para mostrar."/>}</div>}
function Empty({title}:{title:string}){return <div className="emptyState"><b>{title}</b><span>Probá con otros filtros o volvé más tarde.</span></div>}
