"use client";
import {ChangeEvent,useEffect,useState} from "react";
import {useRouter,useSearchParams} from "next/navigation";
import {WizardHeader} from "@/components/wizard-header";
import {EventInvitationPreview} from "@/components/event-invitation-preview";
import {getBrowserSupabase} from "@/lib/supabase-browser";
import {defaultAgenda,planDetails,type EventDraftInput} from "@/lib/event-drafts";
import {templates,type Template} from "@/lib/templates";
import {defaultTheme,type EventTheme} from "@/lib/event-theme";
import {clearPendingEventDraft,readPendingEventDraft,savePendingEventDraft} from "@/lib/pending-event-draft";
type Draft=EventDraftInput&{theme:EventTheme};type Photo={file:File;preview:string};
const initial:Draft={title:"",eventType:"",date:"",time:"",venue:"",templateSlug:"",plan:"Essential",step:0,agenda:defaultAgenda(),features:[],message:"",dressCode:"",musicUrl:"",theme:defaultTheme};
const types=["Boda","XV","Cumpleaños","Infantil","Baby Shower","Corporativo"];
const category=(type:string)=>type==="Boda"?"Bodas":type==="Infantil"?"Infantiles":type==="Corporativo"?"Corporativos":type;
const options=(type:string)=>type==="Baby Shower"?templates.filter(x=>x.slug==="dreamscape"):templates.filter(x=>x.category===category(type));
const themed=(template:Template):EventTheme=>template.theme==="midnight"||template.theme==="gala"||template.theme==="after"?{primaryColor:"#24191d",accentColor:"#c89e42",fontStyle:"refinada"}:template.theme==="aura"||template.theme==="dream"?{primaryColor:"#3e2340",accentColor:"#b33c71",fontStyle:"princesa"}:defaultTheme;
export function CreateEventWizard(){const router=useRouter(),params=useSearchParams(),[draft,setDraft]=useState<Draft>(initial),[photos,setPhotos]=useState<Photo[]>([]),[notice,setNotice]=useState(""),[saving,setSaving]=useState(false),[ready,setReady]=useState(false);const resume=params.get("resume")==="1";
 useEffect(()=>{(async()=>{try{if(resume){const pending=await readPendingEventDraft();if(pending){setDraft({...pending.draft,theme:pending.draft.theme??defaultTheme} as Draft);setPhotos(pending.photos.map(file=>({file,preview:URL.createObjectURL(file)})));setNotice("Recuperamos tu borrador para que puedas guardarlo.")}}else await clearPendingEventDraft()}catch{if(resume)setNotice("No pudimos recuperar el borrador anterior.")}finally{setReady(true)}})()},[resume]);
 const update=<K extends keyof Draft>(key:K,value:Draft[K])=>setDraft(current=>({...current,[key]:value}));const chooseType=(eventType:string)=>{const template=options(eventType)[0]??templates[0];setDraft(current=>({...current,eventType,templateSlug:template.slug,plan:template.plan,features:planDetails[template.plan].features,theme:themed(template)}))};const chooseTemplate=(template:Template)=>setDraft(current=>({...current,templateSlug:template.slug,plan:template.plan,features:planDetails[template.plan].features,theme:themed(template)}));
 const valid=()=>draft.step===0?!!draft.eventType:draft.step===1?draft.title.trim().length>1:draft.step===2?!!draft.date&&!!draft.time:draft.step===3?draft.venue.trim().length>1:draft.step===4?draft.agenda.every(x=>x.time&&x.title.trim()):draft.step===5?!!draft.templateSlug:draft.step===6?photos.length>0:true;
 const next=()=>{if(!valid())return setNotice("Completá este paso para continuar.");setNotice("");update("step",Math.min(7,draft.step+1))};const submit=async()=>{if(!valid())return setNotice("Completá este paso para crear el evento.");const session=(await getBrowserSupabase()?.auth.getSession())?.data.session;if(!session){await savePendingEventDraft({draft,photos:photos.map(x=>x.file)});router.push(`/login?next=${encodeURIComponent("/crear?resume=1")}`);return}setSaving(true);try{const response=await fetch("/api/events/drafts",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${session.access_token}`},body:JSON.stringify(draft)}),body=await response.json();if(!response.ok)throw new Error(body.error);if(photos.length){const form=new FormData();photos.forEach(photo=>form.append("photos",photo.file));const media=await fetch(`/api/events/${body.event.id}/media`,{method:"POST",headers:{authorization:`Bearer ${session.access_token}`},body:form});if(!media.ok)throw new Error("El evento se creó, pero falló la carga de fotos.")}await clearPendingEventDraft();router.replace(`/eventos/${body.event.id}/editar`)}catch(error){setNotice(error instanceof Error?error.message:"No pudimos crear el evento.")}finally{setSaving(false)}};if(!ready)return null;const preview={title:draft.title,event_type:draft.eventType,starts_at:draft.date&&draft.time?new Date(`${draft.date}T${draft.time}:00-03:00`).toISOString():null,template_slug:draft.templateSlug||"eclat",content:{venue:draft.venue,wizard_step:draft.step,features:draft.features,agenda:draft.agenda,message:draft.message,dressCode:draft.dressCode,musicUrl:draft.musicUrl,theme:draft.theme},photos:photos.map(x=>x.preview)};return <main><WizardHeader/><div className="progress"><span>Paso {draft.step+1} de 8</span><progress value={draft.step+1} max="8"/></div><section className="wizard photoWizard"><div className="wizardPanel"><p className="eyebrow">TU CELEBRACIÓN</p><h1>{["¿Qué vamos a celebrar?","Contanos quién celebra.","¿Cuándo empieza?","¿Dónde se encuentran?","¿Cuál es la agenda?","Elegí una plantilla.","Subí tus fotos.","Últimos detalles."][draft.step]}</h1><Fields draft={draft} photos={photos} update={update} chooseType={chooseType} chooseTemplate={chooseTemplate} setPhotos={setPhotos}/>{notice&&<p className="wizardNotice">{notice}</p>}<div className="wizardActions"><button className="button outline" disabled={!draft.step||saving} onClick={()=>update("step",draft.step-1)}>Volver</button><button className="button dark" disabled={saving} onClick={draft.step===7?submit:next}>{saving?"Guardando…":draft.step===7?"Crear mi evento":"Continuar →"}</button></div></div><EventInvitationPreview event={preview}/></section></main>}
function Fields({draft,photos,update,chooseType,chooseTemplate,setPhotos}:{draft:Draft;photos:Photo[];update:<K extends keyof Draft>(key:K,value:Draft[K])=>void;chooseType:(value:string)=>void;chooseTemplate:(value:Template)=>void;setPhotos:(value:Photo[])=>void}){if(draft.step===0)return <div className="choices">{types.map(type=><button className={draft.eventType===type?"selected":""} onClick={()=>chooseType(type)} key={type}>✦<br/>{type}</button>)}</div>;if(draft.step===1)return <><label>Nombre o título<input value={draft.title} onChange={e=>update("title",e.currentTarget.value)}/></label><label>Mensaje<textarea value={draft.message??""} onChange={e=>update("message",e.currentTarget.value)}/></label></>;if(draft.step===2)return <div className="fieldPair"><label>Fecha<input type="date" value={draft.date} onChange={e=>update("date",e.currentTarget.value)}/></label><label>Hora<input type="time" value={draft.time} onChange={e=>update("time",e.currentTarget.value)}/></label></div>;if(draft.step===3)return <label>Lugar<input value={draft.venue} onChange={e=>update("venue",e.currentTarget.value)}/></label>;if(draft.step===4)return <div className="agendaEditor">{draft.agenda.map((item,index)=><div key={index}><input type="time" value={item.time} onChange={e=>update("agenda",draft.agenda.map((x,i)=>i===index?{...x,time:e.currentTarget.value}:x))}/><input value={item.title} onChange={e=>update("agenda",draft.agenda.map((x,i)=>i===index?{...x,title:e.currentTarget.value}:x))}/></div>)}</div>;if(draft.step===5)return <div className="templatePicker">{options(draft.eventType).map(template=><button className={draft.templateSlug===template.slug?"selected":""} onClick={()=>chooseTemplate(template)} key={template.slug}><span className="templateThumb" style={{backgroundImage:`url(${template.coverImage})`}}/><b>{template.name}</b><small>{template.style}</small></button>)}</div>;if(draft.step===6)return <PhotoPicker photos={photos} setPhotos={setPhotos}/>;return <div className="checks">{planDetails[draft.plan].features.map(feature=><label key={feature}><input type="checkbox" checked={draft.features.includes(feature)} onChange={()=>update("features",draft.features.includes(feature)?draft.features.filter(x=>x!==feature):[...draft.features,feature])}/> {feature}</label>)}</div>}
function PhotoPicker({photos,setPhotos}:{photos:Photo[];setPhotos:(value:Photo[])=>void}){const choose=(event:ChangeEvent<HTMLInputElement>)=>{const added=Array.from(event.currentTarget.files??[]).filter(file=>file.type.startsWith("image/")).slice(0,5-photos.length).map(file=>({file,preview:URL.createObjectURL(file)}));setPhotos([...photos,...added]);event.currentTarget.value=""};return <div className="photoUploader"><label className="upload">{photos.length?"Agregar fotos":"Elegir fotos"}<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={choose}/></label><div className="photoThumbs">{photos.map((photo,index)=><figure key={photo.preview}><img src={photo.preview} alt={`Foto ${index+1}`}/><button onClick={()=>setPhotos(photos.filter(x=>x!==photo))}>×</button></figure>)}</div></div>}
