"use client";
import "./draft-preview.css";
import Link from "next/link";
import {useEffect,useState} from "react";
import {getBrowserSupabase} from "@/lib/supabase-browser";
import {PublicInvitation} from "@/components/public-invitation";
import {OrganizerNav} from "@/components/event-portal";
import type {StoredEvent} from "@/lib/event-types";
async function authFetch(path:string,init?:RequestInit){const token=(await getBrowserSupabase()?.auth.getSession())?.data.session?.access_token;return fetch(path,{...init,headers:{authorization:`Bearer ${token??""}`,...(init?.headers??{})}})}
export function DraftPreview({eventId}:{eventId:string}){const[event,setEvent]=useState<StoredEvent>();const[notice,setNotice]=useState("Cargando vista previa…");const[paying,setPaying]=useState(false);useEffect(()=>{authFetch(`/api/events/${eventId}/draft`).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setEvent(body.event);setNotice("")}).catch(error=>setNotice(error instanceof Error?error.message:"No pudimos cargar la vista previa."))},[eventId]);async function checkout(){setPaying(true);setNotice("");try{const response=await authFetch(`/api/events/${eventId}/checkout`,{method:"POST"});const body=await response.json();if(!response.ok)throw new Error(body.error);window.location.assign(body.checkoutUrl)}catch(error){setNotice(error instanceof Error?error.message:"No pudimos iniciar el pago.");setPaying(false)}}if(!event)return <main className="appPage"><p>{notice}</p></main>;const paid=event.payment_status==="approved";return <main className="draftPreview"><div className="draftNav"><OrganizerNav event={event}/><Link href={`/eventos/${eventId}/editar`}>Editar borrador</Link></div>{notice&&<p className="draftNotice">{notice}</p>}<div className="draftCanvas"><PublicInvitation event={event}/><section className="draftPublish"><p className="eyebrow">{paid?"INVITACIÓN PUBLICADA":"BORRADOR PRIVADO"}</p><h2>{paid?"Tu invitación ya está lista para enviar.":"¿Te gusta cómo quedó?"}</h2><p>{paid?"Ya podés gestionar y copiar los enlaces personales de tus invitados.":event.payment_status==="pending"?"Estamos verificando tu pago. Te avisaremos apenas se publique.":"Publicala con Mercado Pago y habilitá los enlaces individuales para tus invitados."}</p>{paid?<Link className="button pink" href={`/eventos/${eventId}/invitados`}>Ir a invitados</Link>:event.payment_status==="pending"?<Link className="button outline" href={`/eventos/${eventId}`}>Volver al panel</Link>:<button className="button pink" onClick={()=>void checkout()} disabled={paying}>{paying?"Abriendo Mercado Pago…":"Publicar y pagar"}</button>}</section></div></main>}
