"use client";
import "./event-portal.css";
import Link from "next/link";
import {useEffect,useState} from "react";
import {getBrowserSupabase} from "@/lib/supabase-browser";
import {eventDateLabel,type StoredEvent} from "@/lib/event-types";
async function authFetch(path:string){const token=(await getBrowserSupabase()?.auth.getSession())?.data.session?.access_token;return fetch(path,{headers:{authorization:`Bearer ${token??""}`}})}
export function OrganizerNav({event}:{event?:StoredEvent}){return <nav className="organizerNav"><Link href="/mis-eventos">Mis eventos</Link>{event&&<><Link href={`/eventos/${event.id}`}>Resumen</Link><Link href={`/eventos/${event.id}/editar`}>Editar invitación</Link><Link href={`/eventos/${event.id}/invitados`}>Invitados</Link><Link href={`/eventos/${event.id}/rsvp`}>RSVP</Link><Link href={`/eventos/${event.id}/vista-previa`}>Vista previa</Link>{event.payment_status==="approved"&&<Link href={`/e/${event.slug}`} target="_blank">Ver publicada ↗</Link>}</>}</nav>}
export function EventsPortal(){const[events,setEvents]=useState<StoredEvent[]>([]),[notice,setNotice]=useState("Cargando tus eventos…");useEffect(()=>{authFetch("/api/events").then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error);setEvents(body.events);setNotice("")}).catch(e=>setNotice(e instanceof Error?e.message:"No pudimos cargar tus eventos."))},[]);return <main className="appPage"><OrganizerNav/><p className="eyebrow">MIS EVENTOS</p><h1>Tus celebraciones.</h1><Link className="button pink" href="/crear">Crear invitación</Link><p>{notice}</p><div className="eventsGrid">{events.map(event=><article key={event.id}><span className={`paymentBadge ${event.payment_status}`}>{event.payment_status==="approved"?"Publicado":event.payment_status==="pending"?"Pago pendiente":"Borrador"}</span><h2>{event.title}</h2><p>{eventDateLabel(event)} · {event.content.venue}</p><Link href={`/eventos/${event.id}`}>Abrir panel →</Link></article>)}</div></main>}
export function EventDashboard({eventId}:{eventId:string}){const[event,setEvent]=useState<StoredEvent>(),[notice,setNotice]=useState("Cargando evento…");useEffect(()=>{authFetch(`/api/events/${eventId}/draft`).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error);setEvent(body.event);setNotice("")}).catch(e=>setNotice(e instanceof Error?e.message:"No pudimos cargar el evento."))},[eventId]);if(!event)return <main className="appPage"><p>{notice}</p></main>;return <main className="appPage"><OrganizerNav event={event}/><p className="eyebrow">PANEL DEL EVENTO</p><h1>{event.title}</h1><p>/{event.slug} · {eventDateLabel(event)} · {event.content.venue}</p><span className={`paymentBadge ${event.payment_status}`}>{event.payment_status==="approved"?"Publicado":event.payment_status==="pending"?"Pago pendiente":"Borrador"}</span><div className="eventsGrid"><Link className="button dark" href={`/eventos/${event.id}/editar`}>Editar invitación</Link><Link className="button outline" href={`/eventos/${event.id}/invitados`}>Gestionar invitados</Link><Link className="button outline" href={`/eventos/${event.id}/rsvp`}>Configurar RSVP</Link><Link className="button outline" href={`/eventos/${event.id}/vista-previa`}>Vista previa y publicación</Link></div></main>}
