"use client";
import {useEffect,useState,type CSSProperties} from "react";
import {getCountdown} from "@/lib/countdown";
import type {EventContent,StoredEvent} from "@/lib/event-types";
import {templates} from "@/lib/templates";
import {getYouTubeVideoId,youtubeEmbedUrl} from "@/lib/youtube";
import {defaultTheme,isTheme,textColor} from "@/lib/event-theme";
import "./event-invitation-preview.css";
export type InvitationPreviewData=Pick<StoredEvent,"title"|"event_type"|"starts_at"|"template_slug">&{content:EventContent;photos?:string[]};
function Countdown({startsAt,image,preview}:{startsAt:string|null;image:string;preview:boolean}){const[state,setState]=useState(()=>getCountdown(startsAt,preview));useEffect(()=>{const id=setInterval(()=>setState(getCountdown(startsAt,preview)),1000);return()=>clearInterval(id)},[startsAt,preview]);return <section className="eventCountdown" style={{"--countdown-image":`url(${image})`} as CSSProperties}>{state.kind==="pending"?<><p>FALTA MUY POCO</p><div>{[[state.days,"DÍAS"],[state.hours,"HS"],[state.minutes,"MIN"],[state.seconds,"SEG"]].map(([v,l])=><span key={String(l)}><b>{String(v).padStart(2,"0")}</b><small>{l}</small></span>)}</div></>:<><p>{state.kind==="missing"?"CUENTA REGRESIVA":"HOY ES EL DÍA"}</p><strong>{state.kind==="missing"?<>Elegí fecha y hora<br/>para activarla.</>:<>¡Llegó el momento<br/>de celebrar!</>}</strong></>}</section>}
export function EventInvitationPreview({event,label="Vista previa",plan,onCheckout=()=>window.location.assign("/precios"),onEdit=()=>window.scrollTo({top:0,behavior:"smooth"})}:{event:InvitationPreviewData;label?:string;plan?:"Essential"|"Plus"|"Premium";onCheckout?:()=>void;onEdit?:()=>void}){const template=templates.find(x=>x.slug===event.template_slug)??templates[0],cover=event.photos?.[0]||template.coverImage,theme=isTheme(event.content.theme)?event.content.theme:defaultTheme,[music,setMusic]=useState(false),musicId=event.content.features.includes("music")?getYouTubeVideoId(event.content.musicUrl):null,date=event.starts_at?new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"long",year:"numeric"}).format(new Date(event.starts_at)):"Fecha a confirmar",preview=label.length>0,price=(plan??template.plan)==="Premium"?25000:(plan??template.plan)==="Plus"?20000:15000;const style={"--cover-image":`url(${cover})`,"--theme-primary":theme.primaryColor,"--theme-accent":theme.accentColor,"--theme-on-accent":textColor(theme.accentColor),"--theme-font":theme.fontStyle==="princesa"?"cursive":theme.fontStyle==="refinada"?"Georgia,serif":"var(--serif)"} as CSSProperties;return <aside className="invitationPreview" style={style}><span>{label}</span><div className="phoneFrame"><div className="phoneScreen"><div className={`eventInvitation ${template.theme}`}><section className="eventCover"><div><small>{event.event_type}</small><h2>{event.title||"Tu celebración"}</h2><b>{date}</b><span>{event.content.venue||"Lugar a confirmar"}</span>{musicId&&<button className="musicToggle" onClick={()=>setMusic(x=>!x)}>{music?"❚❚ Pausar música":"▶ Activar música"}</button>}</div></section>{music&&musicId&&<iframe className="musicPlayer" title="Música" src={youtubeEmbedUrl(musicId)} allow="autoplay; encrypted-media"/>}<Countdown startsAt={event.starts_at} image={template.countdownImage} preview={preview}/><section><p className="eyebrow">AGENDA</p><div className="invitationAgenda">{event.content.agenda.map(x=><p key={`${x.time}-${x.title}`}><b>{x.time}</b><span>{x.title}</span></p>)}</div></section><section className="invitationRsvp"><p className="eyebrow">RSVP</p><h3>Confirmá tu asistencia</h3><button>Confirmar asistencia</button></section>{preview&&<section className="previewCheckout"><p className="eyebrow">¿TE GUSTA CÓMO QUEDÓ?</p><button onClick={onCheckout}>Publicar — ${price.toLocaleString("es-AR")} →</button><button className="previewEdit" onClick={onEdit}>← Editar invitación</button></section>}</div></div></div></aside>}
