"use client";
import "./guests-manager.css";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { OrganizerNav } from "@/components/event-portal";
import { getBrowserSupabase } from "@/lib/supabase-browser";
import type { StoredEvent } from "@/lib/event-types";
type Guest={id:string;display_name:string;seats:number;status:string;confirmed_seats:number|null}; type EventInfo=Pick<StoredEvent,"id"|"slug"|"title"|"payment_status">; type InviteLink={url:string;code:string};
async function api(path:string,init?:RequestInit){const token=(await getBrowserSupabase()?.auth.getSession())?.data.session?.access_token;return fetch(path,{...init,headers:{"content-type":"application/json",authorization:`Bearer ${token??""}`,...(init?.headers??{})}})}
export function GuestsManager({eventId}:{eventId:string}){
 const[event,setEvent]=useState<EventInfo>();const[guests,setGuests]=useState<Guest[]>([]);const[name,setName]=useState("");const[seats,setSeats]=useState(1);const[notice,setNotice]=useState("Cargando invitados…");const[busy,setBusy]=useState(false);const[links,setLinks]=useState<Record<string,InviteLink>>({});
 const load=useCallback(async()=>{try{const r=await api(`/api/events/${eventId}/guests`),b=await r.json();if(!r.ok)throw new Error(b.error);setGuests(b.guests);setEvent({id:eventId,slug:b.eventSlug,title:b.eventTitle,payment_status:b.paymentStatus});setNotice("")}catch(e){setNotice(e instanceof Error?e.message:"No pudimos cargar los invitados.")}},[eventId]);useEffect(()=>{void load()},[load]);
 async function addGuest(e:FormEvent){e.preventDefault();setBusy(true);try{const r=await api(`/api/events/${eventId}/guests`,{method:"POST",body:JSON.stringify({name,seats})}),b=await r.json();if(!r.ok)throw new Error(b.error);setGuests(x=>[...x,b.guest]);setName("");setSeats(1)}catch(e){setNotice(e instanceof Error?e.message:"No pudimos agregar el invitado.")}finally{setBusy(false)}}
 async function remove(guestId:string){if(!window.confirm("¿Eliminar este invitado y su enlace?"))return;setBusy(true);try{const r=await api(`/api/events/${eventId}/guests?guestId=${encodeURIComponent(guestId)}`,{method:"DELETE"}),b=await r.json();if(!r.ok)throw new Error(b.error);setGuests(x=>x.filter(g=>g.id!==guestId))}catch(e){setNotice(e instanceof Error?e.message:"No pudimos eliminar el invitado.")}finally{setBusy(false)}}
 async function issueLink(guestId:string){setBusy(true);setNotice("");try{const r=await api(`/api/events/${eventId}/guests/${guestId}/link`,{method:"POST"}),b=await r.json();if(!r.ok)throw new Error(b.error);setLinks(x=>({...x,[guestId]:b}))}catch(e){setNotice(e instanceof Error?e.message:"No pudimos generar el enlace.")}finally{setBusy(false)}}
 function invitationMessage(guest:Guest,link:InviteLink){return `¡Hola, ${guest.display_name}!\n\nEstás invitado/a a *${event?.title??"nuestra celebración"}*. ✨\n\nTu tarjeta digital está acá:\n${link.url}\n\nCódigo de acceso: *${link.code}*\n\n¡Esperamos que puedas acompañarnos!`}
 async function copy(guest:Guest,link:InviteLink){try{await navigator.clipboard.writeText(invitationMessage(guest,link));setNotice("Mensaje de invitación copiado, listo para enviar.")}catch{setNotice("No pudimos copiarlo automáticamente.")}}
 const paid=event?.payment_status==="approved";const navEvent=event as unknown as StoredEvent|undefined;
 return <main className="appPage guestManager"><OrganizerNav event={navEvent}/><div className="guestHead"><div><p className="eyebrow">LISTA DE INVITADOS</p><h1>Tu lista, bajo control.</h1><p>Creá un grupo, definí sus cupos y enviá un enlace personal cuando publiques.</p></div>{event&&!paid&&<Link className="button pink" href={`/eventos/${eventId}/vista-previa`}>Publicar invitación</Link>}</div>{!paid&&<div className="guestGate"><b>{event?.payment_status==="pending"?"Estamos verificando tu pago":"Los enlaces se habilitan al publicar"}</b><span>Podés preparar toda la lista ahora. Cuando Mercado Pago apruebe el pago, generás y copiás un enlace seguro por invitado.</span></div>}<form className="guestForm" onSubmit={addGuest}><label>Nombre o grupo<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ej.: Familia Pérez" maxLength={120} required/></label><label>Cupos<select value={seats} onChange={e=>setSeats(Number(e.target.value))}>{Array.from({length:12},(_,i)=><option value={i+1} key={i}>{i+1} {i===0?"persona":"personas"}</option>)}</select></label><button className="button dark" disabled={busy}>Agregar invitado</button></form>{notice&&<p className="guestNotice" role="status">{notice}</p>}<section className="guestTable"><div className="guestRow guestLabels"><span>INVITADO</span><span>ESTADO</span><span>CUPOS</span><span>ENLACE</span></div>{guests.length===0?<p className="emptyGuests">Todavía no agregaste invitados.</p>:guests.map(guest=>{const link=links[guest.id];return <div className="guestRow" key={guest.id}><strong>{guest.display_name}</strong><span className={`guestStatus ${guest.status}`}>{guest.status==="confirmed"?"Confirmado":guest.status==="declined"?"No asiste":"Pendiente"}</span><span>{guest.confirmed_seats??0}/{guest.seats}</span><div className="guestActions">{paid?(link?<><button onClick={()=>void copy(guest,link)}>Copiar mensaje</button><a href={`https://wa.me/?text=${encodeURIComponent(invitationMessage(guest,link))}`} target="_blank" rel="noreferrer">Enviar por WhatsApp</a><button onClick={()=>void issueLink(guest.id)}>Regenerar</button></>:<button onClick={()=>void issueLink(guest.id)} disabled={busy}>Generar enlace</button>):<span className="locked">Se habilita al publicar</span>}<button className="deleteGuest" onClick={()=>void remove(guest.id)} disabled={busy}>Eliminar</button></div>{link&&<div className="issuedLink"><b>Código: {link.code}</b><a href={link.url} target="_blank" rel="noreferrer">{link.url}</a></div>}</div>})}</section></main>
}
