"use client";

import "./public-event.css";
import "./premium-rsvp.css";
import "./rsvp-preferences.css";
import "./rsvp-food.css";
import "./rsvp-food-layout.css";
import "./rsvp-success.css";
import "./rsvp-success-luxury.css";
import "./rsvp-lookup.css";
import "./rsvp-stage.css";
import Link from "next/link";
import { useEffect, useState, type CSSProperties } from "react";
import { useRouter } from "next/navigation";
import { templates } from "@/lib/templates";
import { Header } from "@/components/papeleta";

type Member = { id: string; name: string; attending: boolean | null; foodPreference?: string };
type Ctx = { event: any; group: any; members: Member[]; questions: any[]; answers: { question_id: string; value: any }[] };
type Match = { displayName: string; lookupToken: string };
type Food = "Tradicional" | "Vegetariana" | "Vegana";
const FOODS: { label: Food; icon: "cloche" | "leaf" | "sprout" }[] = [{ label: "Tradicional", icon: "cloche" }, { label: "Vegetariana", icon: "leaf" }, { label: "Vegana", icon: "sprout" }];

function Svg({ kind }: { kind: "check" | "users" | "utensils" | "cloche" | "leaf" | "sprout" | "comment" | "calendar" }) {
  const paths = { check: <path d="m5 12 4 4L19 6" />, users: <><circle cx="9" cy="8" r="3" /><path d="M3 20c.5-4 3-6 6-6s5.5 2 6 6M17 8a3 3 0 0 1 0 6m1 1c2 0 3.5 1.5 4 4" /></>, utensils: <path d="M6 3v8m-3-8v5a3 3 0 0 0 6 0V3m-3 8v10M16 3v18m0-18c3 1 4 4 4 7h-4" />, cloche: <><path d="M4 17h16M6 17a6 6 0 0 1 12 0M12 8V5M3 20h18" /></>, leaf: <><path d="M20 4C11 4 5 8 5 15c0 3 2 5 5 5 7 0 10-7 10-16Z" /><path d="M5 20c3-4 7-7 12-9" /></>, sprout: <><path d="M12 21v-8M12 13C7 13 4 10 4 5c5 0 8 3 8 8Zm0 0c0-5 3-8 8-8 0 5-3 8-8 8Z" /></>, comment: <path d="M21 11.5a8 8 0 0 1-8 8H7l-4 2v-6a8 8 0 1 1 18-4Z" />, calendar: <><rect x="3" y="5" width="18" height="16" rx="2" /><path d="M7 3v4m10-4v4M3 10h18" /></> }[kind];
  return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths}</svg>;
}

export function PublicRsvp({ slug }: { slug: string }) {
  const router = useRouter(); const [ctx, setCtx] = useState<Ctx>(); const [step, setStep] = useState(1); const [attending, setAttending] = useState(true); const [ids, setIds] = useState<string[]>([]); const [answers, setAnswers] = useState<Record<string, any>>({}); const [memberFood, setMemberFood] = useState<Record<string, Food>>({}); const [notice, setNotice] = useState(""); const [query, setQuery] = useState(""); const [matches, setMatches] = useState<Match[]>([]); const [selected, setSelected] = useState<Match>(); const [code, setCode] = useState(""); const [done, setDone] = useState(false);
  const load = async () => { const response = await fetch(`/api/public/events/${slug}/rsvp-context`); const body = await response.json(); if (!response.ok) return setNotice(body.error); setCtx(body); if (body.group) { setIds(body.members.filter((member: Member) => member.attending !== false).map((member: Member) => member.id)); setMemberFood(Object.fromEntries(body.members.filter((member: Member) => member.foodPreference).map((member: Member) => [member.id, member.foodPreference]))); setAnswers(Object.fromEntries(body.answers.map((answer: any) => [answer.question_id, answer.value]))); } };
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (!done) return; const timeout = window.setTimeout(() => router.replace(`/e/${slug}`), 5_000); return () => window.clearTimeout(timeout); }, [done, router, slug]);
  useEffect(() => { if (!ctx || ctx.group) return; const closeOnEscape = (event: KeyboardEvent) => { if (event.key === "Escape") router.replace(`/e/${slug}`); }; window.addEventListener("keydown", closeOnEscape); return () => window.removeEventListener("keydown", closeOnEscape); }, [ctx, router, slug]);
  const search = async (value: string) => { setQuery(value); if (value.length < 2) return setMatches([]); const response = await fetch(`/api/public/events/${slug}/guest-lookup`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ query: value }) }); const body = await response.json(); setMatches(body.matches ?? []); };
  const access = async () => { if (!selected) return; const response = await fetch(`/api/public/events/${slug}/guest-access`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ lookupToken: selected.lookupToken, code }) }); const body = await response.json(); if (!response.ok) return setNotice(body.error); void load(); };
  const foodQuestion = ctx?.questions.find((question) => question.key === "food_preference"); const allergy = ctx?.questions.find((question) => question.key === "dietary_restrictions"); const song = ctx?.questions.find((question) => question.key === "song_request"); const custom = ctx?.questions.filter((question) => !["food_preference", "dietary_restrictions", "song_request"].includes(question.key)) ?? []; const confirmedMembers = ctx?.members.filter((member) => ids.includes(member.id)) ?? []; const count = attending ? confirmedMembers.length : 0;
  const requiresCode = ctx?.event?.guest_access_mode === "name_and_code";
  const fallbackCover = templates.find((template) => template.slug === ctx?.event?.template_slug)?.coverImage ?? templates[0].coverImage;
  const style = { "--rsvp-accent": ctx?.event?.content?.theme?.accentColor ?? "#db3473", "--rsvp-cover": `url(${ctx?.event?.event_media?.[0]?.url || fallbackCover})` } as CSSProperties; const deadline = ctx?.event?.rsvp_deadline && new Intl.DateTimeFormat("es-AR", { day: "numeric", month: "long", year: "numeric" }).format(new Date(ctx.event.rsvp_deadline));
  const nav = (next: number) => { if (next === 4 && attending && confirmedMembers.some((member) => !memberFood[member.id])) return setNotice("Elegí un plato para cada persona que asiste."); setNotice(""); setStep(next); };
  const submit = async () => { if (!ctx) return; const response = await fetch(`/api/public/events/${slug}/rsvp`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ attendeeIds: attending ? ids : [], unnamedAttendees: 0, expectedVersion: ctx.group.response_version, idempotencyKey: crypto.randomUUID() + crypto.randomUUID(), answers: ctx.questions.filter((question) => question.id !== foodQuestion?.id).map((question) => ({ questionId: question.id, value: answers[question.id] ?? null })), memberFoodPreferences: attending ? confirmedMembers.map((member) => ({ memberId: member.id, foodPreference: memberFood[member.id] })) : [] }) }); const body = await response.json(); if (!response.ok) return setNotice(body.error); await load(); setDone(true); };
  const downloadCalendar = () => { if (!ctx?.event.starts_at) return; const start = new Date(ctx.event.starts_at).toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, ""); const ics = `BEGIN:VCALENDAR\nVERSION:2.0\nBEGIN:VEVENT\nDTSTART:${start}\nSUMMARY:${ctx.event.title}\nLOCATION:${ctx.event.content.venue ?? ""}\nEND:VEVENT\nEND:VCALENDAR`; const url = URL.createObjectURL(new Blob([ics], { type: "text/calendar" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "evento.ics"; anchor.click(); URL.revokeObjectURL(url); };
  if (!ctx) return <main className="publicRsvpPage"><section className="rsvpCard lookupCard"><p>Cargando confirmación…</p></section></main>;
  if (!ctx.group) return <main className="publicRsvpPage lookupPage" style={style}><section className="rsvpCard lookupCard" role="dialog" aria-modal="true" aria-labelledby="lookup-title"><button className="lookupClose" type="button" aria-label="Cerrar y volver a la invitación" onClick={() => router.replace(`/e/${slug}`)}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18" /></svg></button><div className="lookupIcon"><Svg kind="users" /></div><div className="lookupHeader"><p className="eyebrow">CONFIRMACIÓN DE ASISTENCIA</p><h1 id="lookup-title">Encontrá tu invitación</h1><p>{requiresCode ? "Buscá tu nombre y luego ingresá el código que recibiste." : "Buscá tu nombre para continuar con tu confirmación."}</p></div><label className="lookupSearch"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" aria-hidden="true"><circle cx="10.8" cy="10.8" r="5.8" /><path d="m15.2 15.2 4 4" /></svg><input autoFocus aria-label="Nombre o apellido" placeholder="Nombre o apellido" value={query} onChange={(event) => void search(event.target.value)} /></label><div className="lookupResults">{matches.map((match) => <button className={selected?.lookupToken === match.lookupToken ? "selected" : ""} key={match.lookupToken} type="button" onClick={() => { setSelected(match); setNotice(""); }}><span>{match.displayName}</span><Svg kind="check" /></button>)}</div>{selected && <div className="lookupAccess"><p className="lookupSelection">Invitación seleccionada <b>{selected.displayName}</b></p>{requiresCode && <label className="lookupCode"><span>Código de acceso</span><input placeholder="Ingresá tu código" value={code} onChange={(event) => setCode(event.target.value.toUpperCase())} autoComplete="one-time-code" /></label>}{!requiresCode && <p className="lookupHint">Ya encontramos tu invitación. Podés continuar con la confirmación.</p>}<button className="rsvpAction" onClick={() => void access()} disabled={requiresCode && code.trim().length < 4}>Continuar <span aria-hidden="true">→</span></button></div>}<p className="rsvpNotice">{notice}</p></section></main>;
  if (done) return <><Header /><main className="publicRsvpPage rsvpSuccessPage" style={style}><section className="rsvpCard success" role="dialog" aria-modal="true" aria-labelledby="success-title"><button className="successClose" aria-label="Volver a la invitación" onClick={() => router.replace(`/e/${slug}`)}>×</button><span className="successMark"><Svg kind="check" /></span><p className="eyebrow">CONFIRMACIÓN ENVIADA</p><h1 id="success-title">¡Gracias por confirmar!</h1><p>{attending ? `Registramos ${count} de ${ctx.group.seats} cupos para esta celebración.` : "Registramos que no vas a poder acompañarnos esta vez."}</p><p className="successRedirect">Volverás a la invitación en 5 segundos.</p><div className="successActions"><button className="calendarAction" onClick={downloadCalendar}><Svg kind="calendar" />Agregar al calendario</button><button className="rsvpAction" onClick={() => router.replace(`/e/${slug}`)}>Volver a la invitación <span aria-hidden="true">→</span></button></div></section></main></>;
  return <><Header /><main className={`publicRsvpPage rsvpStage${step === 1 ? " rsvpStageAttendance" : ""}`} style={style}><header className="rsvpHeader"><Link href={`/e/${slug}`}>←</Link><div className="rsvpSteps">{["Asistencia", "Invitados", "Preferencias", "Confirmación"].map((label, index) => <span className={step === index + 1 ? "active" : step > index + 1 ? "complete" : ""} key={label}><i>{step > index + 1 ? "✓" : index + 1}</i><b>{label}</b></span>)}</div></header><div className="rsvpEvent"><p>{ctx.event.event_type}</p><h1>{ctx.event.title}</h1>{deadline && <small>Podés confirmar hasta el {deadline}</small>}</div><section className="rsvpCard premiumRsvp">
    {step === 1 && <><div className="attendanceIntro"><p className="eyebrow">Tu respuesta</p><h1>¿Nos acompañás?</h1><p className="cardLead">Elegí una opción para continuar con tu confirmación.</p></div><div className="rsvpOptions"><button className={attending ? "selected" : ""} aria-pressed={attending} onClick={() => setAttending(true)}><span className="rsvpOptionIcon"><Svg kind="check" /></span><span><small>Confirmar</small><b>¡Sí, voy a estar!</b><em>Reservar mis lugares</em></span></button><button className={!attending ? "selected" : ""} aria-pressed={!attending} onClick={() => setAttending(false)}><span className="rsvpOptionIcon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18" /></svg></span><span><small>No podré asistir</small><b>Esta vez no voy</b><em>Enviar mis disculpas</em></span></button></div><button className="rsvpAction" onClick={() => nav(attending ? 2 : 4)}>Continuar <span aria-hidden="true">→</span></button></>}
    {step === 2 && <><SectionTitle icon="users" title="¿Quiénes van a venir?" text={`Seleccioná hasta ${ctx.group.seats} personas.`} /><div className="memberList">{ctx.members.map((member) => <label key={member.id}><input type="checkbox" checked={ids.includes(member.id)} onChange={() => setIds((current) => current.includes(member.id) ? current.filter((id) => id !== member.id) : current.length < ctx.group.seats ? [...current, member.id] : current)} /><i>{ids.includes(member.id) && <Svg kind="check" />}</i><span>{member.name}</span><small>Invitado</small></label>)}</div><Nav back={() => nav(1)} next={() => nav(3)} /></>}
    {step === 3 && <><SectionTitle icon="utensils" title="Preferencias de comida" text="Elegí el plato de cada persona que asiste." />{confirmedMembers.map((member) => <article className="memberMenu" key={member.id}><div><b>{member.name}</b><span>Elegí su preferencia</span></div><div>{FOODS.map((food) => <button className={memberFood[member.id] === food.label ? "selected" : ""} key={food.label} aria-pressed={memberFood[member.id] === food.label} onClick={() => setMemberFood((current) => ({ ...current, [member.id]: food.label }))}><Svg kind={food.icon} /><span>{food.label}</span></button>)}</div></article>)}<SectionTitle icon="comment" title="Contanos algo más" optional /><label className="preferenceField">Alguna alergia o restricción alimentaria<textarea value={answers[allergy?.id] ?? ""} placeholder="Escribí acá…" onChange={(event) => setAnswers((current) => ({ ...current, [allergy.id]: event.target.value }))} /></label><label className="preferenceField">Alguna canción que no puede faltar<input value={answers[song?.id] ?? ""} placeholder="Escribí el nombre del tema o artista…" onChange={(event) => setAnswers((current) => ({ ...current, [song.id]: event.target.value }))} /></label>{custom.map((question) => <label className="preferenceField" key={question.id}>{question.label}<textarea value={answers[question.id] ?? ""} onChange={(event) => setAnswers((current) => ({ ...current, [question.id]: event.target.value }))} /></label>)}<Nav back={() => nav(2)} next={() => nav(4)} /></>}
    {step === 4 && <><h2>Todo listo</h2><p className="cardLead">{attending ? `${count} de ${ctx.group.seats} cupos · ${confirmedMembers.map((member) => `${member.name}: ${memberFood[member.id]}`).join(" · ")}` : "Registraremos que no podrán asistir."}</p>{deadline && <p className="deadlineNote">Podés modificar tu respuesta hasta el {deadline}.</p>}<button className="calendarAction" onClick={downloadCalendar}><Svg kind="calendar" />Agregar al calendario</button><Nav back={() => nav(attending ? 3 : 1)} next={() => void submit()} label="Confirmar asistencia" /></>}<p className="rsvpNotice">{notice}</p>
  </section></main></>;
}
function SectionTitle({ icon, title, text, optional }: { icon: "users" | "utensils" | "comment"; title: string; text?: string; optional?: boolean }) { return <div className={`rsvpSectionTitle ${optional ? "optional" : ""}`}><Svg kind={icon} /><div><h2>{title} {optional && <small>(opcional)</small>}</h2>{text && <p>{text}</p>}</div></div>; }
function Nav({ back, next, label = "Continuar" }: { back: () => void; next: () => void; label?: string }) { return <div className="rsvpNav"><button className="backButton" onClick={back}>Volver</button><button className="rsvpAction" onClick={next}>{label}</button></div>; }
