import type { EventSections, RsvpConfig } from "./event-types";
import type { EventTheme } from "./event-theme";
export type Plan = "Essential" | "Plus" | "Premium";
export type PaymentStatus = "unpaid" | "pending" | "approved" | "rejected";
export type AgendaItem = { time: string; title: string };
export type EventDraftInput = { title:string; eventType:string; date:string; time:string; venue:string; venueAddress?:string; mapUrl?:string; closingMessage?:string; templateSlug:string; plan:Plan; step:number; agenda:AgendaItem[]; features:string[]; message?:string; dressCode?:string; musicUrl?:string; theme?:EventTheme; rsvp?:RsvpConfig; sections?:EventSections };
export const planDetails:Record<Plan,{price:number;features:string[]}>={Essential:{price:15000,features:["cover","agenda","map","rsvp"]},Plus:{price:20000,features:["cover","agenda","map","rsvp","gallery","gifts","dress-code","music"]},Premium:{price:25000,features:["cover","agenda","map","rsvp","gallery","gifts","dress-code","music","qr","no-branding","priority-support"]}};
export const defaultAgenda=():AgendaItem[]=>[{time:"19:30",title:"Ceremonia"},{time:"21:00",title:"Recepción"},{time:"00:00",title:"Fiesta"}];
export function slugify(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,56)}
export function startsAt(date:string,time:string){const value=new Date(`${date}T${time}:00-03:00`);return Number.isNaN(value.getTime())?null:value.toISOString()}
const url=(value:string|undefined)=>!value||(()=>{try{return new URL(value).protocol==="https:"}catch{return false}})();
const validTheme=(value:unknown)=>!!value&&typeof value==="object"&&/^#[0-9a-fA-F]{6}$/.test((value as EventTheme).primaryColor)&&/^#[0-9a-fA-F]{6}$/.test((value as EventTheme).accentColor)&&(!(value as Partial<EventTheme>).backgroundColor||/^#[0-9a-fA-F]{6}$/.test((value as EventTheme).backgroundColor))&&["clasica","refinada","princesa"].includes((value as EventTheme).fontStyle);
export function validateDraft(input:Partial<EventDraftInput>){if(typeof input.title!=="string"||input.title.trim().length<2||input.title.length>120)return"Ingresá un título de entre 2 y 120 caracteres.";if(!input.eventType?.trim()||input.eventType.length>48)return"Elegí un tipo de evento válido.";if(!input.templateSlug||!/^[a-z0-9-]+$/.test(input.templateSlug))return"Elegí una plantilla válida.";if(!input.plan||!Object.hasOwn(planDetails,input.plan))return"El plan no es válido.";if(!Array.isArray(input.agenda)||!input.agenda.length||input.agenda.some(item=>!/^[0-2]\d:[0-5]\d$/.test(item.time)||!item.title.trim()))return"Completá cada momento de la agenda.";if(input.theme&&!validTheme(input.theme))return"Elegí colores válidos para la identidad visual.";if(!url(input.mapUrl)||!url(input.musicUrl))return"Usá enlaces HTTPS válidos.";if(input.rsvp?.questions.some(question=>!question.key||!question.label.trim()||!(["single_choice","multiple_choice","text"] as string[]).includes(question.kind)||((question.kind!=="text")&&question.options.filter(Boolean).length<2)))return"Revisá las preguntas RSVP y sus opciones.";return null}
export function validatePlanFeatures(plan:Plan,features:string[]){return features.every(feature=>new Set(planDetails[plan].features).has(feature))}
