import { createHmac, timingSafeEqual } from "node:crypto";
import type { NextRequest } from "next/server";
import { planDetails, type Plan } from "./event-drafts";

export type MercadoPagoPayment = { id:number; status:string; external_reference?:string; currency_id?:string; transaction_amount?:number; collector_id?:number; preference_id?:string; metadata?:Record<string,unknown> };

export function mercadoPagoAccessToken() {
  const token=process.env.MERCADOPAGO_ACCESS_TOKEN;
  if(!token) throw new Error("Mercado Pago no está configurado.");
  if(process.env.NODE_ENV==="production"&&process.env.MERCADOPAGO_USE_SANDBOX==="true") throw new Error("Mercado Pago sandbox no puede usarse en producción.");
  return token;
}
export function verifyMercadoPagoSignature(request:NextRequest,paymentId:string){const secret=process.env.MERCADOPAGO_WEBHOOK_SECRET,signature=request.headers.get("x-signature"),requestId=request.headers.get("x-request-id")??"";if(!secret||!signature||!requestId)return false;const values=Object.fromEntries(signature.split(",").map(value=>value.trim().split("=",2)));if(!values.ts||!/^\d+$/.test(values.ts)||!values.v1)return false;const timestamp=Number(values.ts)*1000;if(!Number.isFinite(timestamp)||Math.abs(Date.now()-timestamp)>5*60_000)return false;const manifest=`id:${paymentId.toLowerCase()};request-id:${requestId};ts:${values.ts};`,expected=createHmac("sha256",secret).update(manifest).digest("hex");try{return expected.length===values.v1.length&&timingSafeEqual(Buffer.from(expected),Buffer.from(values.v1))}catch{return false}}
export async function fetchMercadoPagoPayment(paymentId:string){const response=await fetch(`https://api.mercadopago.com/v1/payments/${encodeURIComponent(paymentId)}`,{headers:{Authorization:`Bearer ${mercadoPagoAccessToken()}`},cache:"no-store"});if(!response.ok)throw new Error("No pudimos verificar el pago.");return response.json() as Promise<MercadoPagoPayment>}
export function validatePayment(payment:MercadoPagoPayment,local:{id:string;event_id:string;plan:string;amount:number;provider_preference_id:string|null}){const match=/^papeleta:([0-9a-f-]+):([0-9a-f-]+)$/i.exec(payment.external_reference??"");if(!match||match[1]!==local.id||match[2]!==local.event_id)return"reference_mismatch";if(payment.currency_id!=="ARS"||Number(payment.transaction_amount)!==local.amount)return"amount_or_currency_mismatch";if(!local.provider_preference_id||payment.preference_id!==local.provider_preference_id)return"preference_mismatch";if(!process.env.MERCADOPAGO_USER_ID||String(payment.collector_id)!==process.env.MERCADOPAGO_USER_ID)return"collector_mismatch";const metadata=payment.metadata??{};if(metadata.event_id!==local.event_id||metadata.payment_id!==local.id||metadata.plan!==local.plan)return"metadata_mismatch";return null}
export async function createPreference(input:{paymentId:string;eventId:string;slug:string;title:string;plan:Plan;amount:number;origin:string}){const response=await fetch("https://api.mercadopago.com/checkout/preferences",{method:"POST",headers:{Authorization:`Bearer ${mercadoPagoAccessToken()}`,"Content-Type":"application/json","X-Idempotency-Key":input.paymentId},body:JSON.stringify({items:[{id:input.plan,title:`Papeleta · ${planDetails[input.plan].name} · ${input.title}`,description:`Invitación digital /${input.slug}`,quantity:1,currency_id:"ARS",unit_price:input.amount}],external_reference:`papeleta:${input.paymentId}:${input.eventId}`,metadata:{event_id:input.eventId,payment_id:input.paymentId,slug:input.slug,plan:input.plan},back_urls:{success:`${input.origin}/eventos/${input.eventId}/editar?payment=success`,failure:`${input.origin}/eventos/${input.eventId}/editar?payment=failure`,pending:`${input.origin}/eventos/${input.eventId}/editar?payment=pending`},auto_return:"approved",notification_url:`${input.origin}/api/webhooks/mercadopago`})});const preference=await response.json() as{id?:string;init_point?:string;sandbox_init_point?:string;message?:string};if(!response.ok||!preference.id||!preference.init_point)throw new Error(preference.message??"No pudimos iniciar Mercado Pago.");return{id:preference.id,checkoutUrl:process.env.MERCADOPAGO_USE_SANDBOX==="true"?preference.sandbox_init_point??preference.init_point:preference.init_point}}
