import { createHash } from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import { hasPlanFeature, type Plan } from "@/lib/event-drafts";
import { getAdminSupabase } from "@/lib/public-guest-server";
import { enforceSharedRateLimit } from "@/lib/server-rate-limit";
async function eventFor(slug:string){const db=getAdminSupabase(),{data:event}=await db.from("events").select("id,title,plan,status,payment_status").eq("slug",slug).maybeSingle();return{db,event}}
function available(event:{plan:string;status:string;payment_status:string}|null){return!!event&&event.status==="published"&&event.payment_status==="approved"&&hasPlanFeature(event.plan as Plan,"trivia")}
export async function GET(_request:NextRequest,{params}:{params:Promise<{slug:string}>}){const{slug}=await params,{db,event}=await eventFor(slug);if(!available(event))return NextResponse.json({error:"La trivia no está disponible."},{status:403});const{data}=await db.from("event_trivia_questions").select("id,question,options,position").eq("event_id",event!.id).order("position").limit(50);return NextResponse.json({title:event!.title,questions:data??[]})}
export async function POST(request:NextRequest,{params}:{params:Promise<{slug:string}>}){const{slug}=await params,throttled=await enforceSharedRateLimit(request,"trivia",slug);if(throttled)return throttled;let body:{answers?:unknown;participantToken?:unknown};try{body=await request.json()}catch{return NextResponse.json({error:"Respuesta inválida."},{status:400})}if(!Array.isArray(body.answers)||body.answers.length>50||!body.answers.every(value=>Number.isInteger(value)&&Number(value)>=0&&Number(value)<20)||typeof body.participantToken!=="string"||body.participantToken.length<24||body.participantToken.length>128)return NextResponse.json({error:"Respuesta inválida."},{status:400});const{db,event}=await eventFor(slug);if(!available(event))return NextResponse.json({error:"La trivia no está disponible."},{status:403});const{data:questions}=await db.from("event_trivia_questions").select("id,correct_option").eq("event_id",event!.id).order("position").limit(50);if(body.answers.length!==(questions?.length??0))return NextResponse.json({error:"Completá todas las respuestas."},{status:400});const answers=body.answers as number[],score=(questions??[]).reduce((total,question,index)=>total+(answers[index]===question.correct_option?1:0),0),tokenHash=createHash("sha256").update(body.participantToken).digest("hex");const{error}=await db.from("event_trivia_submissions").insert({event_id:event!.id,answers,score,participant_token_hash:tokenHash});if(error?.code==="23505")return NextResponse.json({error:"Ya participaste desde este navegador."},{status:409});if(error)return NextResponse.json({error:"No pudimos guardar tu resultado."},{status:500});return NextResponse.json({score,total:questions?.length??0})}
