import { NextRequest, NextResponse } from "next/server";
import { hasPlanFeature, type Plan } from "@/lib/event-drafts";
import { getAdminSupabase } from "@/lib/public-guest-server";
import { validateAndSanitizeImage } from "@/lib/server-image-validation";
import { enforceSharedRateLimit } from "@/lib/server-rate-limit";
const MAX_BYTES=3_500_000;
async function context(slug:string){const db=getAdminSupabase(),{data:event}=await db.from("events").select("id,plan,status,payment_status").eq("slug",slug).maybeSingle();return{db,event}}
function available(event:{plan:string;status:string;payment_status:string}|null){return!!event&&event.status==="published"&&event.payment_status==="approved"&&hasPlanFeature(event.plan as Plan,"qr-album")}
export async function GET(_request:NextRequest,{params}:{params:Promise<{slug:string}>}){const{slug}=await params,{db,event}=await context(slug);if(!available(event))return NextResponse.json({error:"El álbum no está disponible."},{status:403});const{data}=await db.from("event_album_photos").select("id,storage_path,created_at").eq("event_id",event!.id).order("created_at",{ascending:false}).limit(500);const photos=await Promise.all((data??[]).map(async photo=>({...photo,url:(await db.storage.from("event-album").createSignedUrl(photo.storage_path,3600)).data?.signedUrl??""})));return NextResponse.json({photos})}
export async function POST(request:NextRequest,{params}:{params:Promise<{slug:string}>}){const{slug}=await params,throttled=await enforceSharedRateLimit(request,"album",slug);if(throttled)return throttled;const{db,event}=await context(slug);if(!available(event))return NextResponse.json({error:"El álbum no está disponible."},{status:403});const form=await request.formData(),files=form.getAll("photos").filter((value):value is File=>value instanceof File);if(!files.length||files.length>5)return NextResponse.json({error:"Subí entre 1 y 5 imágenes."},{status:400});const paths:string[]=[];for(const file of files){let safe;try{safe=await validateAndSanitizeImage(file,MAX_BYTES)}catch{return NextResponse.json({error:"Subí archivos JPEG, PNG o WebP válidos de hasta 3,5 MB."},{status:400})}const path=`${event!.id}/${crypto.randomUUID()}.${safe.extension}`,blob=new Blob([safe.bytes as BlobPart],{type:safe.contentType});const{error:storageError}=await db.storage.from("event-album").upload(path,blob,{contentType:safe.contentType,upsert:false});if(storageError)return NextResponse.json({error:"No pudimos subir la foto."},{status:500});const{error:registerError}=await db.rpc("register_album_photo",{p_event_id:event!.id,p_storage_path:path,p_limit:500});if(registerError){await db.storage.from("event-album").remove([path]);return NextResponse.json({error:registerError.message.includes("album_quota_exceeded")?"El álbum alcanzó su límite.":"No pudimos registrar la foto."},{status:registerError.message.includes("album_quota_exceeded")?409:500})}paths.push(path)}return NextResponse.json({ok:true,count:paths.length},{status:201})}
