import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, type LegalSection } from "@/components/legal-page";
export const metadata:Metadata={title:"Cancelaciones y reembolsos | Papeleta",description:"Arrepentimiento, cancelaciones y reembolsos de Papeleta.",alternates:{canonical:"/reembolsos"}};
const sections:LegalSection[]=[
 {id:"derecho",title:"1. Derecho de arrepentimiento",content:<><p>Si contrataste como consumidor a distancia, podés revocar la aceptación dentro de diez (10) días corridos, computados conforme al artículo 34 de la Ley 24.240 y al artículo 1110 del Código Civil y Comercial. Es irrenunciable y no requiere justificar la decisión.</p><p>Iniciá el trámite desde el <Link href="/arrepentimiento">BOTÓN DE ARREPENTIMIENTO</Link>, sin iniciar sesión.</p></>},
 {id:"excepciones",title:"2. Personalización y uso efectivo",content:<><p>La ley contempla excepciones, incluidos determinados bienes o servicios confeccionados según especificaciones y ciertos suministros digitales. La Disposición 954/2025 también contempla productos o servicios efectivamente utilizados o consumidos.</p><p>No aplicamos una exclusión automática ni una regla general de “sin devolución”. Revisaremos personalización, ejecución, publicación y uso efectivo, preservando siempre los derechos obligatorios.</p></>},
 {id:"incumplimiento",title:"3. Incumplimiento o defectos",content:<p>El arrepentimiento no reemplaza la garantía legal. Si el servicio no coincide con lo ofrecido, no se publica pese a un pago aprobado o presenta un defecto atribuible a Papeleta, podés exigir las alternativas legales: cumplimiento, prestación equivalente o rescisión con restitución, además de daños cuando correspondan.</p>},
 {id:"cobros",title:"4. Cobros duplicados y pagos fallidos",content:<p>Los cobros duplicados o incorrectos se investigarán y restituirán cuando se verifiquen. Un intento rechazado o pendiente no habilita la publicación. Para reconciliar un débito informá el ID de pago; nunca envíes datos completos de tarjeta.</p>},
 {id:"concierge",title:"5. Servicio personalizado",content:<p>“La armamos por vos” se rige también por la propuesta aceptada, que indicará alcance, precio y comienzo. El trabajo realizado puede incidir sólo cuando la ley lo permita y nunca elimina remedios por incumplimiento.</p>},
 {id:"solicitud",title:"6. Cómo solicitarlo",content:<><ol><li>Usá el <Link href="/arrepentimiento">Botón de arrepentimiento</Link> o escribí a <a href="mailto:hola@papeleta.app?subject=Solicitud%20de%20reembolso">hola@papeleta.app</a>.</li><li>Indicá email de compra, ID de pago o evento y tipo de solicitud.</li><li>Podremos pedir una verificación ordinaria exclusivamente por identidad y seguridad.</li></ol><p>Dentro de 24 horas enviaremos por el mismo medio un código de identificación y las medidas adoptadas.</p></>},
 {id:"devolucion",title:"7. Forma de devolución",content:<p>Cuando corresponda, se gestionará por el mismo medio de pago salvo imposibilidad o acuerdo más favorable. Informaremos importe, fecha y referencia. La acreditación final depende de Mercado Pago y la entidad financiera; mantendremos trazabilidad y asistencia.</p>},
 {id:"fuentes",title:"8. Marco normativo",content:<ul><li><a href="https://www.argentina.gob.ar/normativa/nacional/ley-24240-638/actualizacion" target="_blank" rel="noreferrer">Ley 24.240</a>.</li><li><a href="https://www.argentina.gob.ar/normativa/nacional/ley-26994-235975/actualizacion" target="_blank" rel="noreferrer">Código Civil y Comercial</a>.</li><li><a href="https://www.argentina.gob.ar/normativa/nacional/disposici%C3%B3n-954-2025-417152/texto" target="_blank" rel="noreferrer">Disposición 954/2025</a> y <a href="https://www.argentina.gob.ar/normativa/nacional/disposici%C3%B3n-3-2026-423007/texto" target="_blank" rel="noreferrer">Disposición 3/2026</a>.</li></ul>},
];
export default function RefundPolicy(){return <LegalPage eyebrow="COMPRAS Y CANCELACIONES" title="Política de cancelación y reembolsos" lead="Cómo ejercer el arrepentimiento, reportar un cobro incorrecto o pedir una solución." notice={<><strong>No hay una regla general de “sin devolución”.</strong>Cada solicitud se resuelve según el derecho aplicable, el estado real del servicio y la evidencia.</>} sections={sections}/>}
