import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { AnalyticsLink } from "@/components/analytics-link";
import { SiteFooter, SiteHeader } from "@/components/site-shell";
import { TemplateCard } from "@/components/template-card";
import { templates } from "@/lib/templates";

const categories={bodas:{label:"Bodas",singular:"boda",intro:"Diseños elegantes y contemporáneos para compartir cada detalle de su día."},xv:{label:"XV",singular:"fiesta de XV",intro:"Invitaciones con identidad, música y toda la energía de una noche inolvidable."},cumpleanos:{label:"Cumpleaños",singular:"cumpleaños",intro:"Diseños para celebrar una nueva vuelta al sol con tu propio estilo."},infantiles:{label:"Infantiles",singular:"cumple infantil",intro:"Invitaciones alegres, claras y fáciles de compartir con todas las familias."},corporativos:{label:"Corporativos",singular:"evento corporativo",intro:"Una experiencia profesional para convocatorias, galas y encuentros de equipos."}} as const;
type Category=keyof typeof categories;
export function generateStaticParams(){return Object.keys(categories).map((categoria)=>({categoria}))}
export async function generateMetadata({params}:{params:Promise<{categoria:string}>}):Promise<Metadata>{const{categoria}=await params;if(!(categoria in categories))return{};const current=categories[categoria as Category];return{title:`Invitaciones digitales para ${current.label} | Papeleta`,description:`Creá una invitación digital para tu ${current.singular}. Elegí una plantilla, cargá los datos y publicala.`,alternates:{canonical:`/invitaciones/${categoria}`},openGraph:{title:`Invitaciones digitales para ${current.label}`,description:current.intro,url:`/invitaciones/${categoria}`}}}
export default async function Page({params}:{params:Promise<{categoria:string}>}){const{categoria}=await params;if(!(categoria in categories))notFound();const current=categories[categoria as Category];const list=templates.filter((template)=>template.category===current.label);return <main><SiteHeader/><section className="section categoryHero"><p className="eyebrow">INVITACIONES DIGITALES PARA {current.label.toUpperCase()}</p><h1>Tu {current.singular},<br/><em>desde la invitación.</em></h1><p className="lead">{current.intro} Elegí una plantilla, personalizala y publicala cuando esté lista.</p><AnalyticsLink className="button dark" href="/crear" analytics={{name:"create_start",eventType:current.label}}>Crear mi invitación</AnalyticsLink><div className="grid">{list.map((template)=><TemplateCard template={template} key={template.slug}/>)}</div></section><SiteFooter/></main>}
